language: python

python:
  - "3.8"
  - "nightly"

install:
  - pip install poetry
  - python -m poetry install

# just run the tests first
script:
  - python -m pytest tests/

# if the tests succeed, then run full coverage reports
after_success:
  # rerun tests with coverage
  - pip install coverage
  - coverage run --source pyckaxe -m pytest tests/
  # upload to codecov
  - pip install codecov
  - codecov
  # upload to codacy
  - pip install codacy-coverage
  - python-codacy-coverage -r coverage.xml
