[tool.poetry]
name = "pyckaxe"
version = "0.1.0"
description = "An expressive Minecraft utility library revolving around data manipulation and generation."
authors = ["Arcensoth <arcensoth@gmail.com>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/Arcensoth/pyckaxe"
homepage = "https://github.com/Arcensoth/pyckaxe"
keywords = ["minecraft", "commands", "library", "utility", "datapack", "data"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
coverage = "^5.3"
pytest-cov = "^2.10"
pytest = "^6.1"
pyyaml = {version = "^5.3.1", optional = true}
nbtlib = "^1.8.1"
# https://stackoverflow.com/questions/64654805
numpy = "1.19.3"

[tool.poetry.extras]
yaml = ["pyyaml"]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
