# TODO implement type generics and implicit conversions for all types
AdvancementCriteria = str
Block = str
BlockPredicate = Block
CommandTarget = str
CompoundDataTag = str
DataPath = str
Effect = str
Entity = str
EntityAnchor = str
EntityTag = str
GreedyString = str
Item = str
ItemSlot = str
Position = str
Rotation = str
ScoreboardCriteria = str
ScoreboardObjective = str
ScoreboardOperation = str
ScoreboardSlot = str
ScoreHolder = str
Sound = str
SoundSource = str
TextComponent = str
UniqueCommandTarget = str

# Resource location
ResourceLocation = str
AdvancementResourceLocation = ResourceLocation
FunctionResourceLocation = ResourceLocation
